- name: Create a ec2 instance
  hosts: localhost
  gather_facts: False
  vars:
    key_name: ram-keypair
    instance_type: t2.micro
    security_group: ELB
    image: ami-03291866
    region: us-east-2

  tasks:
    - name: Launch instance
      ec2:
         key_name: "{{ key_name }}"
         group: "{{ security_group }}"
         instance_type: "{{ instance_type }}"
         image: "{{ image }}"
         wait: true
         region: "{{ region }}"
         vpc_subnet_id: subnet-0e4f7f18e7296ffa3
         assign_public_ip: yes
      register: ec2

    - name: Add the newly created EC2 instance(s) to the local host group (located inside the directory)
      local_action: lineinfile
        dest="./hosts"
        regexp={{ item.public_ip }}
        insertafter="[webservers]" line={{ item.public_ip }}
      with_items: ec2.instances

    
