- name: Create a ec2 instance
  hosts: localhost
  gather_facts: False
  vars:
    key_name: ram-keypair
    instance_type: t2.micro
    security_group: ELB
    image: ami-03291866
    region: us-east-2

  tasks:
    - name: Launch instance
      ec2:
         key_name: "{{ key_name }}"
         group: "{{ security_group }}"
         instance_type: "{{ instance_type }}"
         image: "{{ image }}"
         wait: true
         region: "{{ region }}"
         vpc_subnet_id: subnet-0e4f7f18e7296ffa3
         assign_public_ip: yes
      register: ec2

    - name: Add the newly created EC2 instance(s) to the local host group (located inside the directory)
      local_action: lineinfile
        dest="./hosts"
        regexp={{ item.public_ip }}
        insertafter="[webserver]" line={{ item.public_ip }}
      with_items: ec2.instances

      - hosts: webservers
        remote_user: ec2-user
        sudo: yes
        tasks:
          - name: install httpd
            yum:
              name=httpd
              update_cache=yes
              state=latest

          - name: install wget
            yum:
              name=wget
              update_cache=yes
              state=latest

          - name: Deploy the static website
            command: wget -O /var/www/html/index.html https://s3.us-east-2.amazonaws.com/apss-test1/index.html
          - name: Ensure httpd is started
            service:
              name: httpd
              state: started
